version: '3.8'

services:
  blog-postgres-dev-db:
    image: postgres:latest
    container_name: blog-postgres-dev-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-blog-db}
    ports:
      - "5432:5432"
    volumes:
      - blog-postgres-dev-db-data:/var/lib/postgresql/data
    networks:
      - blog-network

volumes:
  blog-postgres-dev-db-data:

networks:
  blog-network:
    driver: bridge
